export const products = [
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
    {
        name: "piyush",
        image: "https://yt3.ggpht.com/yti/ANjgQV8FcipRrroXPP6So9rSr4N7XG53ORkKjCBiOHHRMEqQc2Y=s108-c-k-c0x00ffffff-no-rj",
        message: "Hi! How are you",
    },
];

export const chat = [
    {
        name: "Piyush sdjkhfhgjkaskjehfkahsdfuyawefjhsehefiahseifhjasgdfgiuhasjndfgiouawsehfuyawyeuhefgawuihefjhasgiuefgwejsdkfujasjkhdgfjawsgeufgju",
        message: "Hello How are you ",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: true,
    },
    {
        name: "Piyush",
        message: "Hello How are you",
        seen: false,
        time: new Date(),
        self: false,
    },
];
